name: Build and release
on: [push, pull_request]

jobs:
  build_arythmatik:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: ["A-RYTH-MATIK"]
        firmware: ["BitGarden", "Uncertainty", "TimeBandit"]

    steps:
      - name: Clone repo
        uses: actions/checkout@master
        with:
          submodules: recursive

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1.1.1

      - name: Install Arduino platform and libraries
        run: |
          arduino-cli core update-index
          arduino-cli core install arduino:avr
          arduino-cli lib install "Adafruit GFX Library"
          arduino-cli lib install "Adafruit SSD1306"
          arduino-cli lib install SimpleRotary
          arduino-cli lib install FastLED

      - name: Compile sketch and rename output file for release
        working-directory: ./${{ matrix.module}}
        run: |
          arduino-cli compile -v -b arduino:avr:nano ${{ matrix.firmware}} -e --output-dir=./build
          mkdir -p ./release && cp ./build/${{ matrix.firmware }}.ino.hex ./release/${{ matrix.module}}_${{ matrix.firmware }}.hex

      - name: Upload release artifacts
        uses: actions/upload-artifact@v2
        with:
          name: release-artifacts
          path: ./${{ matrix.module}}/release/${{ matrix.module}}_${{ matrix.firmware }}.hex


  build_synclfo:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          module: ["SyncLFO"]
          firmware: ["ADSR", "Baby4", "GenerativeSequencer", "MultiModeEnv", "Polyrhythm"]

    steps:
        - name: Clone repo
          uses: actions/checkout@master

        - name: Setup Arduino CLI
          uses: arduino/setup-arduino-cli@v1.1.1

        - name: Install Arduino platform and libraries
          run: |
            arduino-cli core update-index
            arduino-cli core install arduino:avr

        - name: Compile sketch and rename output file for release
          working-directory: ./${{ matrix.module}}
          run: |
            arduino-cli compile -v -b arduino:avr:nano ${{ matrix.firmware}} -e --output-dir=./build
            mkdir -p ./release && cp ./build/${{ matrix.firmware }}.ino.hex ./release/${{ matrix.module}}_${{ matrix.firmware }}.hex

        - name: Upload release artifacts
          uses: actions/upload-artifact@v2
          with:
            name: release-artifacts
            path: ./${{ matrix.module}}/release/${{ matrix.module}}_${{ matrix.firmware }}.hex

  release:
    needs: [build_arythmatik, build_synclfo]

    runs-on: ubuntu-latest
    steps:
      - name: Download release artifacts
        uses: actions/download-artifact@master
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: release-artifacts
          path: releases/

      - name: Create Release and attach files
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: releases/*.hex
