name: SyncLFO Build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: ["SyncLFO"]
        firmware: ["ADSR", "Baby4", "GenerativeSequencer", "MultiModeEnv", "Polyrhythm"]

    steps:
      - name: Clone repo
        uses: actions/checkout@master
        
      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1.1.1

      - name: Install platform
        run: |
          arduino-cli core update-index
          arduino-cli core install arduino:avr
        
      - name: Compile Sketch
        working-directory: ./${{ matrix.module}}
        run: ARDUINO_DIRECTORIES_USER=$GITHUB_WORKSPACE/${{ matrix.module}} arduino-cli compile -v -b arduino:avr:nano ${{ matrix.firmware}} -e --output-dir=./build

      - name: Upload bin artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.module}}_${{ matrix.firmware }}.hex
          path: ./${{ matrix.module}}/build/${{ matrix.firmware }}.ino.hex
    
      - name: Create Release
        uses: softprops/action-gh-release@v1

      - name: Upload Artifact to release
        uses: fnkr/github-action-ghr@v1
        #if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_PATH: ./${{ matrix.module}}/build/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
